Introduce static open hours for canteens
TUM-Dev/eat-api pull request #105
Opened 2022-01-07 10:20 UTC by Philipp000

Resolves #89 

---

### Static approach

Here I added static open hours to all canteens manually, according to the page: https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/

I was also trying on parsing the page, however there are different pages for different canteens, and these often only contain the name as reference to a canteen, which seemed error prone to me.

Additionally, there is no unified way on presenting the open hours on the webpage e.g.:
![image](https://user-images.githubusercontent.com/1690395/148528582-80921dd6-abda-417f-ba72-adf400d34e09.png)
![image](https://user-images.githubusercontent.com/1690395/148528604-736b13e5-fd24-4a36-953f-46cb6e735ed2.png)
![image](https://user-images.githubusercontent.com/1690395/148528617-f0c3fe6a-11bd-4b0e-8171-78a518be5fa8.png)

Besides the different times given, the format sometimes includes whitespaces or different kinds of separators ("–", "-")

I thought, the times won't change that often, and therefore static open hours should be sufficient.
If you have any other idea, on how to approach this, I would be happy to know it.

### Format
Example in `canteens.json` output:

```
{
    "enum_name": "MENSA_ARCISSTR",
    "name": "Mensa Arcisstra\u00dfe",
    "location": {
      "address": "Arcisstra\u00dfe 17, M\u00fcnchen",
      "latitude": 48.14742,
      "longitude": 11.56722
    },
    "canteen_id": "mensa-arcisstr",
    "queue_status": null,
    "open_hours": {
      "mon": {
        "start": "11:00",
        "end": "14:00"
      },
      "tue": {
        "start": "11:00",
        "end": "14:00"
      },
      "wed": {
        "start": "11:00",
        "end": "14:00"
      },
      "thu": {
        "start": "11:00",
        "end": "14:00"
      },
      "fri": {
        "start": "11:00",
        "end": "14:00"
      }
    }
  }
```

I added a single field for every day, with opening and closing times. The time itself is a string with the format `\d\d:\d\d` so there will always be a leading zero, and 24hr format.

While the webpage shows a more compact version e.g. "Mo-Fr 11:00-14:00"  I think, such a behavior should be managed in the corresponding application displaying the information.

Sometimes, there are special times given for the lecture free period ("Vorlesungsfreie Zeit"), however I wasn't sure on how to handle such edge cases, so I dismissed this information for now.

2022-01-08 13:17 UTC, COM8 reviewed
Looks good. I also agree we do not really care about special opening hours since the target audience are students which check it via the TCA usually only during the semester.
What do you think about adding a link to the website hosting the opening hours?

It's probably the best to merge this one after #101.

2022-01-09 10:23 UTC, Philipp000 commented
Actually, I'm not sure where you think about adding the link to the website for the opening hours?
In the API, for each canteen individually, like:
https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/
https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/garching/
?
I wouldn't do this, as I don't think it adds any valuable information? Or do you thought of something different?

Agree, it would be best, to then also add the documentation.

2022-01-10 19:12 UTC, COM8 commented
I thought of it from an application user perspective. The old Windows Phone 7 App also had opening hours. If you clicked on them you landed on the respective page for the canteen (e.g. https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/).
But I agree. It does not introduce too much value so I'd say we do not include them.

2022-01-24 08:03 UTC, Philipp000 commented
I have now updated the documentation, so this PR should be ready to merge

2022-01-24 15:18 UTC, COM8 requested changes
Only a few minor wording changes left

2022-01-24 15:18 UTC, COM8 commented on openapi.yml
> +      description: specifies a open plan for a whole week (mon-fri)
```suggestion
      description: specifies the opening hours for a whole working week (mon-fri)
```

2022-01-25 08:26 UTC, Philipp000 commented on openapi.yml
> +      description: specifies a open plan for a whole week (mon-fri)
Makes sense, that seems more readable

2022-01-25 08:26 UTC, Philipp000 commented on openapi.yml
> +      description: Specifies, a time range for open hours. Times always are in the format
I have also included this

2022-01-25 08:27 UTC, Philipp000 commented
The wording is now updated, and should be ready to merge

2022-01-26 17:52 UTC, COM8 approved these changes
Thanks!

2022-01-26 17:52 UTC, merged